# Query routing configuration
# Only contains routing/classification logic

response_type_detection:
  content_keywords:
    orders_summary: ["order", "orders"]
    loyalty_summary: ["loyalty", "card", "loyalty card"]
    wallet_summary: ["wallet", "balance"]
    customer_summary: ["customer", "name", "email"]
  type_mapping:
    orders_summary: "orders_summary"
    loyalty_summary: "loyalty_summary"
    wallet_summary: "wallet_summary"
    customer_summary: "customer_summary"

classification_rules:
  keywords:
    live_only:
      - "order"
      - "payment"
      - "customer"
      - "address"
      - "shipping"
      - "billing"
    common_only:
      - "loyalty"
      - "wallet"
      - "ledger"
      - "points"
      - "balance"
      - "card"
      - "card number"
    requires_ledger:
      - "ledger"
      - "history"
      - "transaction"
      - "balance"
      - "points"
      - "amount"
      - "expiry"
    basic_card_only:
      - "card"
      - "card number"
      - "loyalty card"

prompt_templates:
  live:
    order: "show {limit}orders{fields} for customer {customer_id}"
    payment: "show payment information for customer {customer_id}"
    customer: "show customer information for customer {customer_id}"
    address: "show address information for customer {customer_id}"
    shipping: "show shipping information for customer {customer_id}"
    billing: "show billing information for customer {customer_id}"
  common:
    loyalty: "show loyalty card details for customer {customer_id}"
    wallet: "show wallet balance for customer {customer_id}"
    ledger: "show loyalty ledger for customer {customer_id}"
    points: "show loyalty points for customer {customer_id}"
    balance: "show balance information for customer {customer_id}"

field_extraction:
  orders_summary:
    order_amount: ["order_amount", "amount"]
    customer_name: ["customer_name", "name"]
    status: ["status"]
    created_at: ["created_at", "date"]
  loyalty_summary:
    card_number: ["card_number", "card"]
    status: ["status"]
    points_balance: ["points", "balance"]
    expiry_date: ["expiry", "expiry_date"]
  wallet_summary:
    customer_balance: ["balance", "customer_balance"]
    cashback_balance: ["cashback"]
    credits_balance: ["credits"]
    transactions: ["transactions"]

query_scoping:
  both_databases:
    live_prompt_suffix: " (only fetch from orders, payments, customers)"
    common_prompt_suffix: " (only fetch from loyalty, wallet, ledger)"
    common_basic_suffix: " (only fetch loyalty card number)"
  fallback_queries:
    loyalty_card_basic: "SELECT clc.card_number FROM customer_loyalty_card clc WHERE clc.customer_id = {customer_id};"
    loyalty_card_with_ledger: "SELECT clc.card_number, cll.amount, cll.order_id FROM customer_loyalty_card clc JOIN customer_wallet cw ON clc.customer_id = cw.customer_id LEFT JOIN customer_loyalty_ledger cll ON cw.entity_id = cll.wallet_id WHERE clc.customer_id = {customer_id};"

response_combination:
  merge_strategies:
    orders_and_loyalty: "separate_responses"
    orders_only: "orders_summary"
    loyalty_only: "loyalty_summary"
    customer_only: "customer_summary"
    default: "text_response" 