orders_summary:
  fields:
    - order_id
    - amount
    - status
    - date
    - details_url

loyalty_summary:
  fields:
    - card_id
    - tier
    - points
    - history_url

customer_profile:
  fields:
    - customer_id
    - name
    - email
    - phone

mixed_summary:
  fields:
    - orders_summary
    - loyalty_summary

text_response:
  fields:
    - message
