orders_summary:
  fields:
    - orders
    - customer_name

loyalty_summary:
  fields:
    - card_number
    - activation_date
    - expiry_date
    - status

wallet_summary:
  fields:
    - loyalty_points
    - credits_points

text_response:
  fields:
    - message
