orders_summary:
  fields:
    - increment_id
    - amount
    - status

loyalty_summary:
  fields:
    - card_number

customer_profile:
  fields:
    - entity_id
    - email
    - first_name

mixed_summary:
  fields:
    - orders
    - loyalty_card
    - customer

text_response:
  fields:
    - message
